// Datos compartidos para DirectorioLocal CR
window.CR_DATA = {
  cantonActual: { slug: 'aserri', nombre: 'Aserrí', provincia: 'San José' },
  distritoActual: { slug: 'vuelta-de-jorco', nombre: 'Vuelta de Jorco' },
  distritos: [
    { slug: 'aserri-centro', nombre: 'Aserrí Centro', proveedores: 24 },
    { slug: 'tarbaca', nombre: 'Tarbaca', proveedores: 8 },
    { slug: 'vuelta-de-jorco', nombre: 'Vuelta de Jorco', proveedores: 17 },
    { slug: 'san-gabriel', nombre: 'San Gabriel', proveedores: 12 },
    { slug: 'legua', nombre: 'Legua', proveedores: 5 },
    { slug: 'monterrey', nombre: 'Monterrey', proveedores: 9 },
    { slug: 'salitrillos', nombre: 'Salitrillos', proveedores: 14 },
  ],
  categorias: [
    { slug: 'fontaneria', nombre: 'Fontanería', en: 'Plumbing', icon: '💧', count: 6 },
    { slug: 'electricidad', nombre: 'Electricidad', en: 'Electrical', icon: '⚡', count: 4 },
    { slug: 'limpieza', nombre: 'Limpieza', en: 'Cleaning', icon: '🧽', count: 8 },
    { slug: 'jardineria', nombre: 'Jardinería', en: 'Gardening', icon: '🌿', count: 5 },
    { slug: 'reparaciones', nombre: 'Reparaciones', en: 'Repairs', icon: '🔧', count: 3 },
  ],
  proveedores: [
    {
      slug: 'don-rafa-fontaneria', nombre: 'Don Rafa — Fontanería',
      categoria: 'fontaneria', verificado: true, foto: 'rafa',
      desc: 'Fontanero con 18 años atendiendo Aserrí. Reparación de fugas, instalación de tanques y trabajos de emergencia.',
      cantonAtiende: ['Aserrí', 'Desamparados'],
      distritosAtiende: ['Vuelta de Jorco', 'San Gabriel', 'Legua', 'Aserrí Centro'],
      tel: '8712-4490', whatsapp: '50687124490',
      años: 18, trabajos: 340, rating: 4.9, reseñas: 47,
      respuesta: '~12 min', sinpe: true, finSemana: true, hoy: true,
      reseña: { autor: 'María L.', distrito: 'Vuelta de Jorco', texto: 'Vino el mismo día que lo llamé. Trabajo limpio y precio justo.' },
    },
    {
      slug: 'electroservicios-jorco', nombre: 'Electroservicios Jorco',
      categoria: 'electricidad', verificado: true, foto: 'electro',
      desc: 'Instalaciones residenciales, paneles eléctricos y emergencias. Atendemos Vuelta de Jorco y alrededores.',
      cantonAtiende: ['Aserrí'],
      distritosAtiende: ['Vuelta de Jorco', 'Salitrillos', 'Monterrey'],
      tel: '7045-2218', whatsapp: '50670452218',
      años: 9, trabajos: 156, rating: 4.8, reseñas: 28,
      respuesta: '~25 min', sinpe: true, finSemana: false, hoy: true,
      reseña: { autor: 'Carlos M.', distrito: 'Salitrillos', texto: 'Profesionales y puntuales. Hicieron el cambio de panel sin enredos.' },
    },
    {
      slug: 'limpieza-pura-vida', nombre: 'Limpieza Pura Vida',
      categoria: 'limpieza', verificado: false, foto: 'limpieza',
      desc: 'Equipo de tres personas para limpiezas profundas, mudanzas y mantenimiento semanal en casas de la zona.',
      cantonAtiende: ['Aserrí'],
      distritosAtiende: ['Vuelta de Jorco', 'San Gabriel'],
      tel: '6234-7781', whatsapp: '50662347781',
      años: 4, trabajos: 89, rating: 4.6, reseñas: 19,
      respuesta: '~1 h', sinpe: true, finSemana: true, hoy: false,
      reseña: { autor: 'Ana R.', distrito: 'San Gabriel', texto: 'Dejaron la casa impecable después de la mudanza.' },
    },
    {
      slug: 'jardines-don-meco', nombre: 'Jardines Don Meco',
      categoria: 'jardineria', verificado: true, foto: 'jardin',
      desc: 'Mantenimiento de jardines, chapea, poda y siembra. Trabajo de finca también.',
      cantonAtiende: ['Aserrí', 'Acosta'],
      distritosAtiende: ['Vuelta de Jorco', 'Legua', 'Tarbaca'],
      tel: '8845-1102', whatsapp: '50688451102',
      años: 22, trabajos: 410, rating: 4.9, reseñas: 63,
      respuesta: '~30 min', sinpe: true, finSemana: true, hoy: true,
      reseña: { autor: 'José P.', distrito: 'Tarbaca', texto: 'Don Meco conoce la zona como nadie. Trabajo siempre serio.' },
    },
    {
      slug: 'multi-reparaciones-cr', nombre: 'Multi Reparaciones CR',
      categoria: 'reparaciones', verificado: true, foto: 'reparaciones',
      desc: 'Reparaciones generales: portones, techos, cerraduras y pequeñas remodelaciones.',
      cantonAtiende: ['Aserrí', 'Desamparados', 'Alajuelita'],
      distritosAtiende: ['Vuelta de Jorco', 'Salitrillos', 'Monterrey', 'San Gabriel'],
      tel: '7188-6634', whatsapp: '50671886634',
      años: 7, trabajos: 122, rating: 4.7, reseñas: 22,
      respuesta: '~45 min', sinpe: true, finSemana: false, hoy: true,
      reseña: { autor: 'Lucía V.', distrito: 'Monterrey', texto: 'Arreglaron el portón eléctrico en una visita.' },
    },
    {
      slug: 'fontaneria-emergencia-24', nombre: 'Fontanería Emergencia 24',
      categoria: 'fontaneria', verificado: true, foto: 'emerg',
      desc: 'Servicio de emergencia 24/7 para fugas y obstrucciones en zona sur de San José.',
      cantonAtiende: ['Aserrí', 'Desamparados'],
      distritosAtiende: ['Vuelta de Jorco', 'San Gabriel', 'Salitrillos'],
      tel: '8990-1147', whatsapp: '50689901147',
      años: 6, trabajos: 198, rating: 4.7, reseñas: 31,
      respuesta: '~8 min', sinpe: true, finSemana: true, hoy: true,
      reseña: { autor: 'Roberto F.', distrito: 'Vuelta de Jorco', texto: 'A las 11pm me solucionaron una fuga grande.' },
    },
  ],
  i18n: {
    es: {
      buscar: 'Buscar servicio…',
      buscarPlaceholder: '¿Qué necesitás? Ej: fontanero, jardinero',
      ubicacion: 'Ubicación',
      cambiar: 'Cambiar',
      categorias: 'Categorías',
      verTodos: 'Ver todos',
      verificado: 'Verificado',
      llamar: 'Llamar',
      whatsapp: 'WhatsApp',
      proveedores: 'proveedores',
      provincia: 'Provincia',
      canton: 'Cantón',
      distrito: 'Distrito',
      home: 'Inicio',
      servicios: 'Servicios',
      filtros: 'Filtros',
      hoy: 'Disponible hoy',
      soloVerif: 'Solo verificados',
      sinpe: 'Acepta SINPE',
      finde: 'Atiende fines de semana',
      mejores: 'Mejor calificados',
      ordenar: 'Ordenar',
      reseñas: 'reseñas',
      años: 'años en',
      trabajos: 'trabajos',
      respuesta: 'Responde en',
      areaServicio: 'Área de servicio',
      acerca: 'Acerca del proveedor',
      verPerfil: 'Ver perfil',
      reseñasTitulo: 'Reseñas de clientes',
      verTodas: 'Ver todas',
      vacioTitulo: 'Aún no tenemos proveedores en esta categoría',
      vacioTexto: 'Esta es una categoría nueva en el directorio. Si das este servicio en la zona, registrate y aparecé acá.',
      registrarme: 'Registrarme como proveedor',
      cercanos: 'En distritos cercanos',
      empiezaAqui: 'Encontrá servicios cerca de tu casa',
      registrarse: 'Sos proveedor',
      reportar: 'Reportar',
    },
    en: {
      buscar: 'Search service…',
      buscarPlaceholder: 'What do you need? e.g. plumber, gardener',
      ubicacion: 'Location',
      cambiar: 'Change',
      categorias: 'Categories',
      verTodos: 'See all',
      verificado: 'Verified',
      llamar: 'Call',
      whatsapp: 'WhatsApp',
      proveedores: 'providers',
      provincia: 'Province',
      canton: 'Canton',
      distrito: 'District',
      home: 'Home',
      servicios: 'Services',
      filtros: 'Filters',
      hoy: 'Available today',
      soloVerif: 'Verified only',
      sinpe: 'Accepts SINPE',
      finde: 'Open weekends',
      mejores: 'Top rated',
      ordenar: 'Sort',
      reseñas: 'reviews',
      años: 'years in',
      trabajos: 'jobs',
      respuesta: 'Replies in',
      areaServicio: 'Service area',
      acerca: 'About the provider',
      verPerfil: 'View profile',
      reseñasTitulo: 'Client reviews',
      verTodas: 'See all',
      vacioTitulo: 'No providers yet in this category',
      vacioTexto: 'This is a new category in the directory. If you offer this service in the area, register and show up here.',
      registrarme: 'Register as a provider',
      cercanos: 'In nearby districts',
      empiezaAqui: 'Find services near your home',
      registrarse: 'Are you a provider?',
      reportar: 'Report',
    },
  },
};
